cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: canrad.dong@gmail.com
      failed_login_attempts: 2
      first_name: admin
      last_name: admin
      logged_in: false
      password: $2b$12$Slt3VUtQTs4Op2cIYpnGoetCLOVI/c.eoGwZ1v4uvVXXaMQ1xqHG2
      password_hint: huiyuan
      roles: null
pre-authorized:
  emails:
  - melsby@gmail.com
